services:
  mediataapp:
    build: .
    container_name: mediataapp_prod
    env_file:
      - ./dotenv_files/.env.prod
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./mediataapp:/mediataapp
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    depends_on:
      - psql
    restart: unless-stopped

  nginx:
    container_name: nginx_prod
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/web/static:/data/web/static:ro
      - ./data/web/media:/data/web/media:ro
      - ./certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - mediataapp
    command: ["/bin/sh", "-c", "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./var/run/docker.sock:/var/run/docker.sock:ro
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "trap exit TERM;
       while :; do
         certbot renew --webroot -w /var/www/certbot --quiet;
         docker exec nginx_prod nginx -s reload;
         sleep 12h & wait $${!};
       done"

  psql:
    container_name: psql_prod
    image: postgres:15-alpine
    env_file:
      - ./dotenv_files/.env.prod
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_prod:
    driver: local




    
