services:
  mediataapp:
    build: .
    container_name: mediataapp_prod
    env_file:
      - ./dotenv_files/.env.prod
    volumes:
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    ports:
      - "80:8000"
    environment:
      - ENVIRONMENT=production
    depends_on:
      - psql
    restart: unless-stopped

  psql:
    container_name: psql_prod
    image: postgres:15-alpine
    env_file:
      - ./dotenv_files/.env.prod
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_prod:
    driver: local