services:
  mediataapp:
    build: .
    container_name: mediataapp_dev
    env_file:
      - ./dotenv_files/.env.dev
    volumes:
      - ./mediataapp:/mediataapp
      - ./data/web/static:/data/web/static
      - ./data/web/media:/data/web/media
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    depends_on:
      - psql

  psql:
    container_name: psql_dev
    image: postgres:15-alpine
    env_file:
      - ./dotenv_files/.env.dev
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev:
    driver: local
