# Generated by Django 5.2.4 on 2025-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumo', models.CharField()),
                ('codigo', models.CharField(max_length=6)),
                ('tipo', models.CharField(choices=[('S', 'Serviço'), ('M', 'Material'), ('O', 'Mão de Obra'), ('E', 'Equipamento')], max_length=1)),
                ('valor_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
