# Generated by Django 5.2.4 on 2025-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='codigo',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='insumo',
            field=models.CharField(max_length=255),
        ),
    ]
