# Generated by Django 5.2.4 on 2025-07-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_alter_insumos_codigo_alter_insumos_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumos',
            name='taxa',
        ),
        migrations.AddField(
            model_name='insumos',
            name='quant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='tipo',
            field=models.CharField(choices=[('S', 'Serviço'), ('M', 'Material'), ('O', 'Mão de Obra'), ('E', 'Equipamento'), ('T', 'Taxa')], max_length=1),
        ),
    ]
