# Generated by Django 5.2.4 on 2025-07-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_remove_insumos_taxa_insumos_quant_alter_insumos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='quant',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
