# Generated by Django 5.2.4 on 2025-08-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_alter_insumos_quant'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='unidade',
            field=models.CharField(blank=True, choices=[('UN', 'Unidade'), ('PC', 'Peça'), ('CJ', 'Conjunto'), ('PAR', 'Par'), ('DZ', 'Dúzia'), ('KG', 'Quilograma'), ('G', 'Grama'), ('MG', 'Miligrama'), ('T', 'Tonelada'), ('L', 'Litro'), ('ML', 'Mililitro'), ('M3', 'Metro cúbico'), ('M', 'Metro'), ('CM', 'Centímetro'), ('MM', 'Milímetro'), ('KM', 'Quilômetro'), ('M2', 'Metro quadrado'), ('CM2', 'Centímetro quadrado'), ('HA', 'Hectare'), ('CX', 'Caixa'), ('SC', 'Saca'), ('ROLO', 'Rolo'), ('BALDE', 'Balde'), ('TUBO', 'Tubo')], max_length=5, null=True),
        ),
    ]
