# Generated by Django 5.2.4 on 2025-08-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0005_insumos_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='codigo',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
