# Generated by Django 5.2.4 on 2025-08-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0006_alter_insumos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='valor_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
