# Generated by Django 5.2.17 on 2026-10-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0007_alter_insumos_valor_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='unidade',
            field=models.CharField(blank=True, choices=[('10M', '10 Metros (10M)'), ('18L', '18 Litros (18L)'), ('200KG', '200 Quilogramas (200KG)'), ('310ML', '310 Mililitros (310ML)'), ('50KG', '50 Quilogramas (50KG)'), ('AS', 'Atividade semanal (AS)'), ('BALDE', 'Balde (BALDE)'), ('BD', 'Balde (BD)'), ('BARRA', 'Barra (BARRA)'), ('CX', 'Caixa (CX)'), ('CM', 'Centímetro (CM)'), ('CM2', 'Centímetro quadrado (CM2)'), ('CENTO', 'Cento (CENTO)'), ('CJ', 'Conjunto (CJ)'), ('CHI', 'Custos horários improdutivos (CHI)'), ('CHP', 'Custos horários produtivos (CHP)'), ('DM3', 'Decímetro cúbico (DM3)'), ('DIA', 'Dia (DIA)'), ('DZ', 'Dúzia (DZ)'), ('FL', 'Folha (FL)'), ('GL', 'Galão (GL)'), ('G', 'Grama (G)'), ('HA', 'Hectare (HA)'), ('H', 'Hora (H)'), ('JG', 'Jogo (JG)'), ('LT', 'Latão (LT)'), ('L', 'Litro (L)'), ('MES', 'Mês (MES)'), ('M', 'Metro (M)'), ('M3', 'Metro cúbico (M3)'), ('M3XKM', 'Metro cúbico x quilômetro (M3XKM)'), ('M/MES', 'Metro por mês (M/MES)'), ('M2', 'Metro quadrado (M2)'), ('M2/MES', 'Metro quadrado por mês (M2/MES)'), ('MG', 'Miligrama (MG)'), ('MIL', 'Milheiro (MIL)'), ('ML', 'Mililitro (ML)'), ('MM', 'Milímetro (MM)'), ('PCT', 'Pacote (PCT)'), ('PAR', 'Par (PAR)'), ('PC', 'Peça (PC)'), ('PÇ', 'Peça (PÇ)'), ('pp.', 'Porcentagem (pp.)'), ('KG', 'Quilograma (KG)'), ('KM', 'Quilômetro (KM)'), ('KW/H', 'Quilowatt por hora (KW/H)'), ('RL', 'Rolo (RL)'), ('ROLO', 'Rolo (ROLO)'), ('SC', 'Saca (SC)'), ('SACO', 'Saco (SACO)'), ('SC25KG', 'Saco de 25 Quilogramas (SC25KG)'), ('S', 'Serviço (S)'), ('T', 'Tonelada (T)'), ('T/KM', 'Tonelada por quilômetro (T/KM)'), ('TXKM', 'Tonelada x quilômetro (TXKM)'), ('TUBO', 'Tubo (TUBO)'), ('UN', 'Unidade (UN)'), ('VB', 'Valor base (VB)'), ('VG', 'Valor global (VG)'), ('V', 'Vara (V)')], max_length=6, null=True),
        ),
    ]
