# Generated by Django 5.2.4 on 2025-08-07 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='razao_social',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='tipo_pessoa',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='agencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='conta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo_chave_pix',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatoria', 'Chave Aleatória')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo_conta',
            field=models.CharField(blank=True, choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Poupança'), ('salario', 'Conta Salário')], max_length=20, null=True),
        ),
    ]
