# Generated by Django 5.2.4 on 2025-08-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_colaborador_cnpj_colaborador_nome_fantasia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
