# Generated by Django 5.2.4 on 2025-08-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0003_colaborador_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
