# Generated by Django 5.2.4 on 2025-08-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0004_colaborador_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
