# Generated by Django 5.2.4 on 2025-07-20 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('O', 'Orçamento'), ('A', 'Aprovado'), ('E', 'Executado'), ('V', 'Vistoriado'), ('F', 'Finalizado'), ('R', 'Rejeitado')], default='L', max_length=1)),
                ('emergencial', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('valor_mao_obra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_faturamento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('ultimo_update', models.DateField(auto_now_add=True)),
                ('finalizado', models.BooleanField(default=False, null=True)),
                ('data_finalizar', models.DateField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
    ]
