# Generated by Django 5.2.4 on 2025-07-23 20:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_options_ticket_valor_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='data_finalizar',
        ),
        migrations.AddField(
            model_name='ticket',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
