# Generated by Django 5.2.4 on 2025-07-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_data_finalizar_ticket_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='data_finalizar',
            field=models.DateField(blank=True, null=True),
        ),
    ]
