# Generated by Django 5.2.4 on 2025-07-25 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_data_finalizar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('L', 'Levantamento'), ('C', 'Cotação'), ('A', 'Aprovado'), ('E', 'Em executado'), ('X', 'Executado'), ('V', 'Vistoriado'), ('F', 'Finalizado'), ('R', 'Rejeitado')], default='L', max_length=1),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Material')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('unidade', models.CharField(max_length=50, verbose_name='Unidade de Medida (ex: sacos, metros)')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitário')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
                'unique_together': {('orcamento', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='MaoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Horas')),
                ('valor_hora', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Hora')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Mão de Obra',
                'verbose_name_plural': 'Mão de Obra',
                'unique_together': {('orcamento', 'descricao')},
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Equipamento')),
                ('tempo_uso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tempo de Uso')),
                ('unidade_tempo', models.CharField(max_length=50, verbose_name='Unidade de Tempo (ex: horas, dias)')),
                ('valor_aluguel_unidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Aluguel por Unidade')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.orcamento', verbose_name='Orçamento')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'unique_together': {('orcamento', 'nome')},
            },
        ),
    ]
