# Generated by Django 5.2.4 on 2025-07-25 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_orcamento_alter_ticket_status_material_maodeobra_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maodeobra',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='maodeobra',
            name='orcamento',
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='material',
            name='orcamento',
        ),
        migrations.DeleteModel(
            name='Equipamento',
        ),
        migrations.DeleteModel(
            name='MaoDeObra',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='Orcamento',
        ),
    ]
