# Generated by Django 5.2.4 on 2025-07-25 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_maodeobra_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcamento', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('valor_material', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento_material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.CharField(max_length=255)),
                ('valor_servico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento_servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.orcamento')),
            ],
        ),
    ]
