# Generated by Django 5.2.4 on 2025-07-25 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_orcamento_material_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='ticket_orcamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
            preserve_default=False,
        ),
    ]
