# Generated by Django 5.2.4 on 2025-07-28 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_orcamento_ticket_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_historico', models.DateTimeField(auto_now_add=True)),
                ('descricao_historico', models.TextField()),
                ('ticket_historico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket')),
            ],
        ),
    ]
