# Generated by Django 5.2.4 on 2025-07-31 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_alter_insumos_quant'),
        ('tickets', '0010_historicoticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('quant', models.IntegerField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insumos.insumos')),
                ('orcamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.orcamento')),
            ],
        ),
    ]
