# Generated by Django 5.2.4 on 2025-08-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_itemorcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoticket',
            name='descricao_historico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
