# Generated by Django 5.2.4 on 2025-08-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticket_valor_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='valor_custo',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valor_faturamento',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valor_mao_obra',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valor_material',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10),
        ),
    ]
