# Generated by Django 5.2.4 on 2025-08-05 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticket_valor_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('L', 'Levantamento'), ('C', 'Cotação'), ('A', 'Aprovado'), ('E', 'Em execução'), ('X', 'Executado'), ('V', 'Vistoriado'), ('F', 'Finalizado'), ('R', 'Rejeitado')], default='L', max_length=1),
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('M', 'Material'), ('O', 'Mão de Obra'), ('E', 'Equipamento')], max_length=1, null=True)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status_pagamento', models.BooleanField(default=False)),
                ('ticket_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.ticket')),
            ],
        ),
    ]
