# Generated by Django 5.2.4 on 2025-08-07 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('tickets', '0015_alter_ticket_status_pagamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente'),
        ),
    ]
