# Generated by Django 5.2.4 on 2025-08-08 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0002_colaborador_cnpj_colaborador_nome_fantasia_and_more'),
        ('tickets', '0016_ticket_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='colaborador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colaborador.colaborador'),
        ),
    ]
