# Generated by Django 5.2.4 on 2025-08-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_ticket_valor_custo_alter_ticket_valor_mao_obra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='data_pagamento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='ticket_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='tipo',
            field=models.CharField(choices=[('M', 'Material'), ('S', 'Serviço'), ('O', 'Mão de Obra'), ('E', 'Equipamento'), ('T', 'Taxa')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='valor_pagamento',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
