# Generated by Django 5.2.4 on 2025-08-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_pagamentos_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='valor_equipamento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
