# Generated by Django 5.2.4 on 2025-08-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_ticket_valor_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='nfe_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
