# Generated by Django 5.2.4 on 2025-08-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_ticket_nfe_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='valor_pagamento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Pagamento'),
        ),
    ]
