# Generated by Django 5.2.4 on 2025-08-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_alter_pagamentos_valor_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='comprovante',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
