# Generated by Django 5.2.4 on 2025-08-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_pagamentos_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='data_update_pagamento',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
