# Generated by Django 5.2.4 on 2025-08-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_pagamentos_data_update_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='data_update_pagamento',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
