# Generated by Django 5.2.4 on 2025-08-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0026_orcamento_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='ticket_pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='tickets.ticket'),
        ),
    ]
