# Generated by Django 5.2.6 on 2025-09-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_alter_pagamentos_ticket_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
