# Generated by Django 5.2.7 on 2026-02-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_ticket_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='anexo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='anexo2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
