# Generated by Django 5.2.7 on 2026-02-25 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0029_ticket_anexo_ticket_anexo2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='anexo2',
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos/')),
                ('descricao_anexo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('ticket_anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='tickets.ticket')),
            ],
        ),
    ]
