# Generated by Django 5.2.7 on 2026-03-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0030_remove_ticket_anexo_remove_ticket_anexo2_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recebimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('serie_nota_fiscal', models.CharField(blank=True, max_length=255, null=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_recebimento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_recebimento', models.BooleanField(choices=[(True, 'Recebido'), (False, 'a receber')], default=False)),
                ('descricao_recebimento', models.CharField(blank=True, max_length=255, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('À vista', 'À vista'), ('Parcelado', 'Parcelado')], max_length=30, null=True)),
                ('tipo_pagamento', models.CharField(blank=True, choices=[('Cartão de Crédito', 'Cartão de Crédito'), ('Cartão de Débito', 'Cartão de Débito'), ('Transferência Bancária', 'Transferência Bancária'), ('Pix', 'Pix'), ('Cheque', 'Cheque'), ('Boleto', 'Boleto'), ('Outro', 'Outro')], max_length=30, null=True)),
                ('comprovante_recebimento', models.CharField(blank=True, max_length=255, null=True)),
                ('data_recebimento', models.DateTimeField(auto_now_add=True, null=True)),
                ('ticket_recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='tickets.ticket')),
            ],
        ),
    ]
