# Generated by Django 5.2.7 on 2026-03-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0031_recebimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimentos',
            name='data_recebimento_realizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recebimentos',
            name='recebimento_realizado',
            field=models.BooleanField(default=False),
        ),
    ]
