# Generated by Django 5.2.7 on 2026-03-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_recebimentos_data_recebimento_realizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebimentos',
            name='status_recebimento',
            field=models.BooleanField(choices=[(True, 'Recebido'), (False, 'a Receber')], default=False),
        ),
    ]
