# Generated by Django 5.2.15 on 2026-06-28 12:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_alter_recebimentos_status_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorcamento',
            name='quant',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10),
        ),
    ]
