# Generated by Django 5.2.15 on 2026-07-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0034_alter_itemorcamento_quant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recebimentos',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('À vista', 'À vista'), ('A Prazo', 'A Prazo')], max_length=30, null=True),
        ),
    ]
